# Generated by Django 5.2.3 on 2025-08-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isHome',
            field=models.BooleanField(default=False),
        ),
    ]
